version: '3'

services:
  mloader:
    build:
      context: .
      dockerfile: Dockerfile-source
    restart: unless-stopped
    environment:
      - SRC_REPO=https://github.com/darodi/mloader.git
      - BRANCH_NAME=develop
    volumes:
      - ./mloader:/usr/src/app/mloader
      - ./mloader-download-source.sh:/usr/src/app/mloader-download.sh

